check the code.
WALWALASAFI/tribute-page pull request #1
Opened 2024-05-23 16:11 UTC by WALWALASAFI

please review code  changes and approve

2024-05-24 05:08 UTC, WALWALASAFI commented
Hi sir, 
i hope ur fie, kindly check my project
@ahzamir
@ahzia

2024-05-24 10:58 UTC, WALWALASAFI commented
the code checked correctly in free code camp and have no linter error.
![un7952210_20220919_lf_1683_](https://github.com/WALWALASAFI/tribute-page/assets/168632281/11387c9d-764a-4213-bb1c-3fdc986ff0e0)
is there anything remind for approving the project dear sir,
@ahzamir
@ahzia 

thanks in advance!

2024-05-24 11:02 UTC, WALWALASAFI commented
the code have been checked and accepted in free code camp. Also have no linter error.
is there anything remind for approving the project.
dear sir, 
 @ahzamir
@ahzia
thanks in advance! 
![Uploading Annotation 2024-05-24 152356.png…]()

2024-05-24 12:03 UTC, ahzamir requested changes
### Hi @WALWALASAFI 🙋‍♀️,

> Excellent work! You have done a great job implementing the project requirements but your project still misses some of the requirements:

- Although your code passes all the checks on freecodecamp website, but your HTML code is not clean please check the comments below for more details.

# Status: Required Changes 🔁
Make changes to your code and commit and request for a re-review.

![AlmostThereReachGIF](https://github.com/LimaSahibzada/Survey-Form-project1/assets/96838030/4f0a3cd6-3a46-4e1e-8e31-ef617d4e8ac3)

 ## Highlights 🌞
 
🎯 Great Design implemented.
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed and completed the Tribute Page and all requirements.
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
❌ Your code is clean

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

2024-05-24 12:03 UTC, ahzamir commented on index.html
> + </main>
@WALWALASAFI 

- Although your code passes the feecodecamp and meets all the requirements , butyour code is still not clean:
- And for cleaning your code:
  - At the bottom right side of your vscode click on `Spaces` then click on `Index using spaces` and choose 2 from there.
  - Then according to the lines on the screen all child elements should be 2 spaces or one line ahead of their parent element and the closing tag should be in the same line as the opening tag!
  
  - Your body spacing is not aligned correctly:
  - All child elements should be two spaces ahead of their parent element.

**Example:**
```
<div>
  <h1> ... </h1>
  <p>
  .
  .
  </p>
  <div>
    <img ... />
    more elements ...
  </div>
</div>
```

2024-05-24 12:03 UTC, ahzamir commented on style.css
- Add some more design to your page and elements so it looks more amazing to share.

2024-05-25 06:51 UTC, WALWALASAFI commented
hi dear sir,
i have done correct. what u said.
and about style.css i linked it with my html  however it commited and pushed but doesnt apper on page. when .
this is my style.css.
<img width="960" alt="style .css="https://github.com/WALWALASAFI/tribute-page/assets/168632281/fd85fa47-d95f-4e8e-9b41-9f54301b3108">
@ahzamir

2024-05-25 10:39 UTC, ahzamir requested changes
@WALWALASAFI 

- Your both projects have spacing issues, ask your partner to help you with that.

2024-05-25 14:18 UTC, WALWALASAFI commented
@ahzamir
sir is it cleaned now, i added some style and linked it style.css with index.html,but when i see in google. it didnt link!

2024-05-26 12:47 UTC, ahzamir commented
> @ahzamir sir is it cleaned now, i added some style and linked it style.css with index.html,but when i see in google. it didnt link!

- The issue is in your CSS file naming your CSS file name is `style.css.css`  which is wrong rename your CSS file and change it to `style.css`.

2024-05-26 12:48 UTC, ahzamir approved these changes
### Hi @WALWALASAFI 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text on it with a screenshot.

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

![GreatJobThumbsUpGIF](https://github.com/ZuhRa-HashiMi/survey-form/assets/96838030/cc459d3f-5796-43f0-aba7-4ed0c35fa276)

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Tribute Page project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

2024-05-26 13:09 UTC, merged

2024-05-26 13:11 UTC, WALWALASAFI commented
much obliged dear sir
oh my gosh, i got so happy 
i am working on technical-documention project.
inshallah this project wont have any problem.